// Generated by https://github.com/StirlingMarketingGroup/go2ts

// accounts.go
declare enum TaxShelter {
    Taxable = "TAXABLE",
    Traditional = "TRADITIONAL",
    Roth = "ROTH",
    HSA = "HSA",
    FiveTwentyNine = "529",
}

declare interface Account {
    account_id?: number;
    name: string;
    description?: string;
    tax_shelter: TaxShelter;
    institution: string;
    is_deprecated: boolean;
    user_id: number;
    created_at: string;
    updated_at: string;
}

declare interface CreateAccountResponse {
    data: {
        account: Account;
    };
    error: string;
}

declare interface GetAccountsResponse {
    data: {
        accounts: Account[];
        pagination: PaginationMetadata;
    };
    error: string;
}

declare interface GetAccountResponse {
    data: {
        account: Account;
    };
    error: string;
}

declare interface UpdateAccountResponse {
    data: {
        account: Account;
    };
    error: string;
}

declare interface DeleteAccountResponse {
    data: {
        message: string;
        account: Account;
    };
    error: string;
}

// auth.go

declare interface RegisterResponse {
    data: {
        user: User;
    };
    error: string;
}

declare interface LoginResponse {
    data: {
        token: string;
        user: User;
    };
    error: string;
}

declare interface GetMeResponse {
    data: {
        user: User;
    };
    error: string;
}

// benchmark.go

declare enum AssetCategory {
    Cash = "CASH",
    Bills = "BILLS",
    STB = "STB",
    ITB = "ITB",
    LTB = "LTB",
    Commodities = "COMMODITIES",
    Gold = "GOLD",
    REITS = "REITS",
    TSM = "TSM",
    DLCB = "DLCB",
    DLCG = "DLCG",
    DLCV = "DLCV",
    DLCM = "DLCM",
    DMCB = "DMCB",
    DMCG = "DMCG",
    DMCV = "DMCV",
    DMCM = "DMCM",
    DSCG = "DSCG",
    DSCB = "DSCB",
    DSCV = "DSCV",
    DSCM = "DSCM",
    ILCB = "ILCB",
    ILCG = "ILCG",
    ILCV = "ILCV",
    ILCM = "ILCM",
    IMCB = "IMCB",
    IMCG = "IMCG",
    IMCV = "IMCV",
    IMCM = "IMCM",
    ISCB = "ISCB",
    ISCG = "ISCG",
    ISCV = "ISCV",
    ISCM = "ISCM",
    Crypto = "CRYPTO",
    Other = "OTHER",
}

declare interface AssetAllocationPct {
    category: AssetCategory;
    percent: number;
}

declare interface Benchmark {
    benchmark_id: number;
    name: string;
    description: string;
    asset_allocation: AssetAllocationPct[];
    std_dev_pct: number;
    real_return_pct: number;
    drawdown_yrs: number;
    rec_rebalance_threshold_pct: number;
    is_deprecated: boolean;
    user_id: number;
    created_at: string;
    updated_at: string;
}

declare interface CreateBenchmarkResponse {
    data: {
        benchmark: Benchmark;
    };
    error: string;
}

declare interface GetBenchmarksResponse {
    data: {
        benchmarks: Benchmark[];
        pagination: PaginationMetadata;
    };
    error: string;
}

declare interface GetBenchmarkResponse {
    data: {
        benchmark: Benchmark;
    };
    error: string;
}

declare interface UpdateBenchmarkResponse {
    data: {
        benchmark: Benchmark;
    };
    error: string;
}

declare interface DeleteBenchmarkResponse {
    data: {
        message: string;
        benchmark: Benchmark;
    };
    error: string;
}

// holding.go

declare interface Holding {
    holding_id?: number;
    name: string;
    ticker?: string;
    asset_category: AssetCategory;
    expense_ratio_pct?: number;
    maturation_date?: string;
    interest_rate_pct?: number;
    is_deprecated: boolean;
    user_id: number;
    created_at: string;
    updated_at: string;
}

declare interface CreateHoldingResponse {
    data: {
        holding: Holding;
    };
    error: string;
}

declare interface GetHoldingsResponse {
    data: {
        holdings: Holding[];
        pagination: PaginationMetadata;
    };
    error: string;
}

declare interface GetHoldingResponse {
    data: {
        holding: Holding;
    };
    error: string;
}

declare interface UpdateHoldingResponse {
    data: {
        holding: Holding;
    };
    error: string;
}

declare interface DeleteHoldingResponse {
    data: {
        message: string;
        holding: Holding;
    };
    error: string;
}

// pagination.go

declare interface PaginationMetadata {
    current_page: number;
    page_size: number;
    total_items: number;
}

declare interface PaginationQuery {
    current_page: number;
    page_size: number;
}

// snapshot_value.go

declare interface SnapshotValue {
    snap_val_id: number;
    snap_id: number;
    account_id: number;
    holding_id: number;
    total: number;
    skip_rebalance: boolean;
    user_id: number;
    created_at: string;
    updated_at: string;
}

declare interface CreateSnapshotValueResponse {
    data: {
        snapshot_value: SnapshotValue;
    };
    error: string;
}

declare interface GetSnapshotValuesResponse {
    data: {
        snapshot_values: SnapshotValue[];
    };
    error: string;
}

declare interface GetSnapshotValueResponse {
    data: {
        snapshot_value: SnapshotValue;
    };
    error: string;
}

declare interface UpdateSnapshotValueResponse {
    data: {
        snapshot_value: SnapshotValue;
        snapshot_total: number;
        snapshot_weighteder: number;
    };
    error: string;
}

declare interface DeleteSnapshotValueResponse {
    data: {
        snapshot_value: SnapshotValue;
        snapshot_total: number;
        snapshot_weighteder: number;
        message: string;
    };
    error: string;
}

// snapshot.go

declare interface Snapshot {
    snap_id: number;
    description?: string;
    snap_date: string;
    total: number;
    weighted_er_pct: number;
    rebalance_threshold_pct: number;
    benchmark_id?: number;
    user_id: number;
    created_at: string;
    updated_at: string;
}

declare interface ResourcesGrouped {
    fields: string[];
    total: number[];
}

declare interface MaturationDateResource {
    account_name: string;
    holding_name: string;
    asset_category: string;
    interest_rate_pct: number;
    maturation_date: string;
    total: number;
    skip_rebalance: boolean;
}

declare interface LiquidityResource {
    account_name: string;
    holding_name: string;
    asset_category: string;
    ticker: string;
    institution: string;
    tax_shelter: string;
    total: number;
}

declare interface AssetAllocation {
    category: string;
    value: number;
}

declare interface CreateSnapshotResponse {
    data: {
        snapshot: Snapshot;
        snapshot_values: SnapshotValue[];
    };
    error: string;
}

declare interface GetSnapshotResponse {
    data: {
        snapshot: Snapshot;
        snapshot_values: SnapshotValue[];
        accounts: Account[];
        holdings: Holding[];
    };
    error: string;
}

declare interface GetSnapshotsResponse {
    data: {
        snapshots: Snapshot[];
        pagination: PaginationMetadata;
    };
    error: string;
}

declare interface GetSnapshotAccountsResponse {
    data: {
        accounts_grouped: ResourcesGrouped;
        field_type: string;
    };
    error: string;
}

declare interface GetSnapshotHoldingsResponse {
    data: {
        holdings_grouped: ResourcesGrouped;
        field_type: string;
    };
    error: string;
}

declare interface GetSnapshotMaturationDateResponse {
    data: {
        resources: MaturationDateResource[];
        field_type: string;
        maturation_start: string;
        maturation_end: string;
    };
    error: string;
}

declare interface GetSnapshotLiquidityResponse {
    data: {
        resources: LiquidityResource[];
        liquid_total: string;
        field_type: string;
    };
    error: string;
}

declare interface GetSnapshotRebalanceResponse {
    data: {
        target_allocation?: AssetAllocation[];
        current_allocation?: AssetAllocation[];
        change_required?: AssetAllocation[];
        rebalance_deviation_pct: number;
        needs_rebalance: boolean;
        snapshot_total: number;
        snapshot_total_omit_skips: number;
    };
    error: string;
}

declare interface UpdateSnapshotResponse {
    data: {
        snapshot: Snapshot;
    };
    error: string;
}

declare interface DeleteSnapshotResponse {
    data: {
        message: string;
        snapshot: Snapshot;
    };
    error: string;
}

// user.go
declare enum UserRole {
    Default = "DEFAULT",
    Admin = "ADMIN",
}

declare interface User {
    user_id?: number;
    email: string;
    user_role: UserRole;
    last_logged_in: string;
    verified: boolean;
    created_at: string;
    updated_at: string;
}

declare interface GetUserByIdResponse {
    data: {
        user: User;
    };
    error: string;
}

declare interface DeleteUserResponse {
    data: {
        message: string;
        user: User;
    };
    error: string;
}