ALTER TYPE asset_type ADD VALUE 'DLCM' AFTER 'DLCV';
ALTER TYPE asset_type ADD VALUE 'DMCM' AFTER 'DMCV';
ALTER TYPE asset_type ADD VALUE 'DSCM' AFTER 'DSCV';
ALTER TYPE asset_type ADD VALUE 'ILCM' AFTER 'ILCV';
ALTER TYPE asset_type ADD VALUE 'IMCM' AFTER 'IMCV';
ALTER TYPE asset_type ADD VALUE 'ISCM' AFTER 'ISCV';